# Lab Week 4
In lab work\
January 27, 2020

In [1]:
# using python as a calculator
3+5*4

23

In [4]:
weight_kg = 60

In [10]:
print(weight_kg)
print(weight_kg^2)
# not weight squared
print(weight_kg*weight_kg)
# weight squared
print(weight_kg**2)
# another weight squared
# you can't have a variable starting with a number, also case sensitive
# i.e.
# no 0weight
# weight0 different from Weight0

60
62
3600
3600


In [16]:
my_number = 3
my_float = 2.434343
my_string = 'This is my string'
# in python you can do single or double quotes
# i.e. my_string = "This is my string" is the same as above
my_string = 'This is my cool floating point number:'

In [17]:
print(my_string, my_float)

This is my cool floating point number: 2.434343


In [22]:
weight_kg_text = 'weight in kilograms:'
print(weight_kg_text, weight_kg)
print("weight in pounds:", weight_kg*2.2)
print(weight_kg)
weight_kg = 100
print(weight_kg)

weight in kilograms: 100
weight in pounds: 220.00000000000003
100
100


In [24]:
x = 5
y = 6
print(x+y)

11


In [25]:
x = y
print(x+y)

12


In [26]:
mass = 47.5
age = 122
mass = mass * 2
age = age - 20
print(mass, age)

95.0 102


In [27]:
first, second = 'Grace', 'Shawn'
third, fourth = second, first
print(third, fourth)

Shawn Grace


In [28]:
import numpy
# import, +name of module

In [29]:
numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')
# dot notation
# anything that comes after dot is a numpy function

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.]])

In [30]:
medical_data = numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

In [31]:
print(medical_data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]]


In [32]:
import numpy as np
# session will know numpy as np and not numpy (if not previously imported)

In [34]:
medical_data = np.loadtxt(fname='inflammation-01.csv', delimiter=',')

In [35]:
a = [1,2,3,4]
# array

In [36]:
print(a)

[1, 2, 3, 4]


In [37]:
print(a[0])
# first element in an array is indexed by 0
# second element in an array is 1
# if you do print(a[4]), you'll get IndexError
# list index out of range

1


In [39]:
print(a[3])

4


In [40]:
print(medical_data.dtype)
# what's your data type

float64


## data types
ints = 3, 6, 100\
floating point numbers = 3.245, 1.2, 354.45422

In [42]:
print(medical_data.shape)
# outputs (rows,columns)

(54, 40)


In [43]:
print('first value in medical data:', medical_data[0,0])

first value in medical data: 0.0


In [44]:
print('middle value in data:', medical_data[30,20])

middle value in data: 6.0


In [47]:
med_data_shape = medical_data.shape
print(med_data_shape)

(54, 40)


In [48]:
print(med_data_shape[0])

54


In [51]:
middle_row = int(med_data_shape[0]/2)
middle_col = int(med_data_shape[1]/2)
# casting, explicitly change the data type
# i.e. force int()
print(middle_row, middle_col)

27 20


In [50]:
print('actual middle of data:', medical_data[middle_row, middle_col])

actual middle of data: 6.0


In [53]:
zz = 4.2342343
print(zz)
print(int(zz))

4.2342343
4


In [58]:
print(medical_data[0:4,0:10])
# 0 to the 4th element

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]]


In [61]:
bruin = medical_data[:3, 36:]
print('bruin is:\n', bruin)

bruin is:
 [[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [62]:
print(np.mean(medical_data))

5.658333333333333


In [64]:
import time
print(time.ctime())
# function with no parameters
# functions always followed by parentheses

Mon Jan 27 09:42:37 2020


In [65]:
maxval, minval = np.max(medical_data), np.min(medical_data)
stdval = np.std(medical_data)

In [67]:
print('max:', maxval, ', min:', minval, ', stdev:', stdval)

max: 19.0 , min: 0.0 , stdev: 4.352194529455482
