# Week Four HW Part 1: preliminary analyses
Whitney Tsai Nakashima

In [6]:
import numpy as np

In [7]:
import pandas as pd

In [ ]:
tmp_data = 

In [20]:
color_data = np.loadtxt(fname='Tangara-color-illustrations.csv', delimiter=',', skiprows=1, usecols=np.arange(4,17))

# color data for tanager illustrations
# each column is an illustration of a bird species
# column 1 (index 0) is the average number of colors on that bird
# all other columns are presence (1)/ absence (0), of a particular color
# order of colors: Red,Orange,Yellow,Green,Blue,Indigo,Violet,Gray,Black,Brown,White,Buff

In [21]:
print(color_data)

[[5. 0. 0. ... 0. 0. 1.]
 [4. 0. 0. ... 0. 0. 1.]
 [4. 0. 0. ... 0. 0. 1.]
 ...
 [3. 0. 0. ... 0. 1. 1.]
 [5. 0. 0. ... 0. 0. 1.]
 [4. 0. 0. ... 0. 0. 1.]]


In [22]:
print(color_data.dtype)

float64


In [23]:
print(color_data.shape)

(82, 13)


In [25]:
?np.mean

In [31]:
total_colors = color_data[:,0]
# select column 1 (index 0), total number of colors on a bird

In [33]:
print(total_colors)

[5. 4. 4. 5. 3. 3. 3. 2. 4. 5. 3. 4. 5. 5. 4. 5. 7. 5. 7. 5. 4. 6. 3. 6.
 6. 6. 4. 4. 5. 5. 3. 3. 5. 6. 4. 4. 5. 5. 4. 4. 4. 6. 6. 4. 4. 6. 3. 5.
 5. 5. 4. 4. 4. 6. 5. 5. 3. 4. 4. 7. 4. 6. 6. 4. 3. 4. 5. 5. 6. 2. 3. 2.
 5. 5. 6. 4. 3. 5. 4. 3. 5. 4.]


In [34]:
mean_total_colors = np.mean(total_colors)
print('Mean number of colors on a tanager illustration:', mean_total_colors)

Mean number of colors on a tanager illustration: 4.487804878048781


In [36]:
Tangara_abbas = color_data[0, 1:]
# select row 1 (index 0), Tangara abbas data
print(Tangara_abbas)

[0. 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1.]


In [38]:
Tangara_abbas_num_colors = np.sum(Tangara_abbas)
print('Number of colors present on Tangara abbas illustration:', Tangara_abbas_num_colors)

Number of colors present on Tangara abbas illustration: 5.0
