# Week 4 HW Part 2
Whitney Tsai Nakashima

## Slicing strings

A section of an array is called a slice. We can take slices of character strings as well:

In [4]:
element = 'oxygen'
print('first three characters:', element[0:3])
print('last three characters:', element[3:6])

first three characters: oxy
last three characters: gen


'oxyg'

### Question 1

What are the values of:

In [10]:
print('The first four characters:', element[:4])
print('The last two characters (5th character on):',element[4:])
print('All characters:', element[:])

The first four characters: oxyg
The last two characters (5th character on): en
All characters: oxygen


### Question 2

What about the values of:

In [12]:
print('The last character:', element[-1])
print('The second to last character:', element[-2])

The last character: n
The second to last character: e


### Question 3

Given these answers, explain what element[1:-1] does.

It should print 'xyge' because it is printing index 1 (x) to index -1 (n) without including the last indexed letter.

In [14]:
print('The second character up to (put not including) the last character:', element[1:-1])

The second character up to (put not including) the last character: xyge


### Question 4

The expression element[3:3] produces an empty string, i.e., a string that contains no characters. 

If data holds our array of patient data, what does data[3:3, 4:4] produce? 

An empty array.


What about data[3:3, :]?

Another empty array.

## Stacking Arrays

Arrays can be concatenated and stacked on top of one another, using NumPy’s vstack and hstack functions for vertical and horizontal stacking, respectively.

In [15]:
import numpy as np

In [17]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
print('A = ')
print(A)

B = np.hstack([A,A])
print('B = ')
print(B)

C = np.vstack([A,A])
print('C = ')
print(C)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


### Question 1

Write some additional code that slices the first and last columns of A, and stacks them into a 3x2 array. Make sure to print the results to verify your solution.

In [33]:
A_first = np.vstack(A[:,0])
print('A first column = ')
print(A_first)
A_last = np.vstack(A[:,-1])
print('A last column =')
print(A_last)
A_mat3x2 = np.hstack([A_first, A_last])

print('A matrix 3x2 = ')
print(A_mat3x2)

A first column = 
[[1]
 [4]
 [7]]
A last column =
[[3]
 [6]
 [9]]
A matrix 3x2 = 
[[1 3]
 [4 6]
 [7 9]]


## Change In Inflammation

This patient data is longitudinal in the sense that each row represents a series of observations relating to one individual. This means that the change in inflammation over time is a meaningful concept.

The numpy.diff() function takes a NumPy array and returns the differences between two successive values along a specified axis. For example, a NumPy array that looks like this:

In [34]:
npdiff = np.array([0,2,5,9,14])

In [35]:
np.diff(npdiff)

array([2, 3, 4, 5])

### Question 1: Which axis would it make sense to use this function along?

It would make the most sense to use this function along axis = 1, because this would compare differences in inflammation over time for one individual.

### Question 2: If the shape of an individual data file is (60, 40) (60 rows and 40 columns), what would the shape of the array be after you run the diff() function and why?

The shape of the array with be (60,39) because the shape of the array is reduced by one column.

### Question 3: How would you find the largest change in inflammation for each patient? Does it matter if the change in inflammation is an increase or a decrease?

I would find the difference between each successive value for each patient. It does matter if there is an increase or decrease in inflammation when trying to calculate the largest change. Therefore, I would take the absolute value of each of the differences to account so that I could return the largest change regardless of direction.

In [45]:
data = np.loadtxt("inflammation-01.csv",delimiter = ",")
np.shape(data)

(54, 40)

In [58]:
data_diff = np.diff(data)
# change in inflammation 
data_diff_abs = np.abs(data_diff)
# change in inflammation regardless of increase or decrease
pat_inflam = np.max(data_diff_abs, axis = 1)
# max change in inflammation for each patient
print('Largest change in inflammation for each patient:')
print(pat_inflam)

Largest change in inflammation for each patient:
[12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11.
 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11.
 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11.]
